ollama:
  api_url: "http://ollama:11434"
  model: "qwen3:8b"
tools:
  - name: "get_precip"
    route: "http://localhost:8125/get_precip"
    description: "get the precipitation for a given city"
    usage: "get_precip(<city name here in plain text>)"
  - name: "get_temp"
    route: "http://localhost:8125/get_temp"
    description: "get the temperature for a given city"
    usage: "get_temp(<city name here in plain text>)"